name: Build & Publish Release APK
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        description: "ref"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name }}
          submodules: 'recursive'
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'frp/go.mod'
          cache-dependency-path: 'frp/go.sum'
      - name: Setup project
        run: |
          make purge_sdk
          make install_sdk
          echo "BUILD_REF=${{ github.event.inputs.ref || github.ref_name }}" >> $GITHUB_ENV
          echo "BUILD_TOOLS_VERSION=$(ls /usr/local/lib/android/sdk/build-tools | sort | tail -n 1)" >> $GITHUB_ENV
      - name: Build Release APKs (universal, arm64, amd64)
        run: make release
      - uses: filippoLeporati93/android-release-signer@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Move APKs
        run: |
          mv -v app/release/app-release-unsigned.apk DroidFRPD-${{ env.BUILD_REF }}-unsigned.apk
          mv -v app/release/app-release-aarch64-unsigned.apk DroidFRPD-${{ env.BUILD_REF }}-aarch64-unsigned.apk
          mv -v app/release/app-release-x86_64-unsigned.apk DroidFRPD-${{ env.BUILD_REF }}-x86_64-unsigned.apk
          mv -v app/release/app-release-unsigned-signed.apk DroidFRPD-${{ env.BUILD_REF }}.apk
          mv -v app/release/app-release-aarch64-unsigned-signed.apk DroidFRPD-${{ env.BUILD_REF }}-aarch64.apk
          mv -v app/release/app-release-x86_64-unsigned-signed.apk DroidFRPD-${{ env.BUILD_REF }}-x86_64.apk
      - name: Upload to release assets
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            DroidFRPD-${{ env.BUILD_REF }}.apk
            DroidFRPD-${{ env.BUILD_REF }}-unsigned.apk
            DroidFRPD-${{ env.BUILD_REF }}-aarch64.apk
            DroidFRPD-${{ env.BUILD_REF }}-aarch64-unsigned.apk
            DroidFRPD-${{ env.BUILD_REF }}-x86_64.apk
            DroidFRPD-${{ env.BUILD_REF }}-x86_64-unsigned.apk
      - name: Upload as artifacts
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: |
            DroidFRPD-${{ env.BUILD_REF }}.apk
            DroidFRPD-${{ env.BUILD_REF }}-unsigned.apk
            DroidFRPD-${{ env.BUILD_REF }}-aarch64.apk
            DroidFRPD-${{ env.BUILD_REF }}-aarch64-unsigned.apk
            DroidFRPD-${{ env.BUILD_REF }}-x86_64.apk
            DroidFRPD-${{ env.BUILD_REF }}-x86_64-unsigned.apk
