name: Build & Publish Release APK
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        description: "ref"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name }}
          submodules: 'recursive'
      - name: Setup project
        run: |
          echo "BUILD_REF=${{ github.event.inputs.ref || github.ref_name }}" >> $GITHUB_ENV
          echo "BUILD_TOOLS_VERSION=$(ls /usr/local/lib/android/sdk/build-tools | sort | tail -n 1)" >> $GITHUB_ENV
          mkdir release
      - name: Build Release APK (universal)
        run: |
          ./gradlew assembleRelease
          mv -v app/build/outputs/apk/release/app-release-unsigned.apk release/
      - name: Build Release APK (aarch64)
        run: |
          echo "frp.disableAmd64 = true" >> local.properties
          ./gradlew assembleRelease
          mv -v app/build/outputs/apk/release/app-release-unsigned.apk release/app-release-aarch64-unsigned.apk
      - name: Build Release APK (x86_64)
        run: |
          sed -i "s/disableAmd64/disableArm64/g" local.properties
          ./gradlew assembleRelease
          mv -v app/build/outputs/apk/release/app-release-unsigned.apk release/app-release-x86_64-unsigned.apk
      - uses: filippoLeporati93/android-release-signer@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}
        with:
          releaseDirectory: release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Move APKs
        run: |
          mv -v release/app-release-unsigned.apk DroidFRPD-${{ env.BUILD_REF }}-unsigned.apk
          mv -v release/app-release-aarch64-unsigned.apk DroidFRPD-${{ env.BUILD_REF }}-aarch64-unsigned.apk
          mv -v release/app-release-x86_64-unsigned.apk DroidFRPD-${{ env.BUILD_REF }}-x86_64-unsigned.apk
          mv -v release/app-release-unsigned-signed.apk DroidFRPD-${{ env.BUILD_REF }}.apk
          mv -v release/app-release-aarch64-unsigned-signed.apk DroidFRPD-${{ env.BUILD_REF }}-aarch64.apk
          mv -v release/app-release-x86_64-unsigned-signed.apk DroidFRPD-${{ env.BUILD_REF }}-x86_64.apk
      - name: Upload to release assets
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            DroidFRPD-${{ env.BUILD_REF }}.apk
            DroidFRPD-${{ env.BUILD_REF }}-unsigned.apk
            DroidFRPD-${{ env.BUILD_REF }}-aarch64.apk
            DroidFRPD-${{ env.BUILD_REF }}-aarch64-unsigned.apk
            DroidFRPD-${{ env.BUILD_REF }}-x86_64.apk
            DroidFRPD-${{ env.BUILD_REF }}-x86_64-unsigned.apk
      - name: Upload as artifacts
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: |
            DroidFRPD-${{ env.BUILD_REF }}.apk
            DroidFRPD-${{ env.BUILD_REF }}-unsigned.apk
            DroidFRPD-${{ env.BUILD_REF }}-aarch64.apk
            DroidFRPD-${{ env.BUILD_REF }}-aarch64-unsigned.apk
            DroidFRPD-${{ env.BUILD_REF }}-x86_64.apk
            DroidFRPD-${{ env.BUILD_REF }}-x86_64-unsigned.apk
